[package]
name = "strawrCli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
dotenv = "0.15.0"
env_logger = "0.11.6"
image = "0.25.5"
log = "0.4.22"
