quiet = false # suppress non-error output
default_editor = "vscode" # "vscode", "zed", "nano", "vim"

[grab]
encrypt_values_by_default = true

[img]
default_format = "webp" # "webp", "jpeg", "png", "original"
default_webp_compression = "lossless" # "lossless", "lossy"
default_webp_quality = 100 # 1 - 100
default_jpg_quality = 100 # 1 - 100
thumbnail_size = 64
blur_intensity = 8
placeholder_size = 64
placeholder_blur_intensity = 6
max_size=1024 # optional
[img.get]
default_color_output="hex" # hex, rgb
[img.gen]
default_ai_model = "dalle2"
default_img_size = "lg"

[template]
frontend_folder_title = "client"
backend_folder_title = "server"